# パラメータ推定

データを最もよく再現するパラメータを推定する。確率モデルのパラメータを最尤推定する方法の1つ。

## 最尤推定

後で紹介するEMアルゴリズムは最尤推定が基本にあるため、紹介。
尤度(もっともらしさ)を最大にする。最ももっともらしい値を推定。

表が 0.3 の確率で出るコイン A と表が 0.8 の確率で出るコイン B があるとする。
A か B か分からないがどちらかのコインを 3 回続けて投げたら、表、裏、表という順番で出た。

- コイン A を使ったときの確率（尤度）は、 `0.3　×　（1－0.3）　×　0.3　＝　0.063`
- コイン B を使ったときの確率（尤度）は、 `0.8　×　（1－0.8）　×　0.8　＝　0.128`

コインBを使った時のほうが確率(尤度)が高い

## EMアルゴリズム

毎回コインA、コインBのどちらも使う可能性も考慮。

http://www.slideshare.net/yag_ays/em-algorithm-animation

- 局所最適解に陥る可能性がある
- 隠れ変数を含むモデルの学習に使われる
- GMM(混合ガウスモデル)の学習では一般的にEMアルゴリズムが使われることが多い

## 実践

In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import mixture

In [2]:
g = mixture.GMM(n_components=2)

In [3]:
obs = np.concatenate((np.random.randn(100, 1), 10 + np.random.randn(300, 1)))

In [4]:
g.fit(obs)

GMM(covariance_type='diag', init_params='wmc', min_covar=0.001,
  n_components=2, n_init=1, n_iter=100, params='wmc', random_state=None,
  thresh=None, tol=0.001, verbose=0)

In [5]:
np.round(g.weights_, 2)

array([ 0.25,  0.75])

In [6]:
np.round(g.means_, 2)

array([[-0.05],
       [ 9.94]])

In [7]:
np.round(g.covars_, 2)

array([[ 0.79],
       [ 0.99]])

In [8]:
g.predict([[0], [2], [9], [10]])

array([0, 0, 1, 1])

In [9]:
np.round(g.score([[0], [2], [9], [10]]), 2)

array([-2.19, -4.83, -1.65, -1.2 ])

## 参考資料

- http://scikit-learn.org/stable/modules/generated/sklearn.mixture.GMM.html
- https://ja.wikipedia.org/wiki/EM%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0